### PR TITLE
change store behavior for laravel nova 2.0

### PR DESCRIPTION
**Pull request by sidigi**
some little changes in laravel nova 2.0 for filters

### CODE REVIEW

**Comment by sidigi** [comment]
Without this it didn't works on laravel nova 2.0

**Comment by skauk** [comment]
2.0?! I'm a bit behind of that :)

**Comment by sidigi** [comment]
Yep)))

Laravel nova 2.0

**Comment by skauk** [comment]
@sidigi Thanks for the contribution! Can you update with composer and let me know it works?

**Comment by sidigi** [comment]
Yes It's a live (It's work)

**Pull request merged**
